=== asclepias/asclepias-broker/jsonschema/event.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/asclepias/event-model/master/jsonschema/event.json",
    "title": "Event message schema.",
    "description": "Schema of the event message.",
    "additionalProperties": false,
    "type": "object",
    "properties": {
        "event_type": {
            "type": "string",
            "description": "Type of the event. Controlled vocabulary: 'relation_created' or 'relation_deleted'",
            "enum": ["relation_created", "relation_deleted", "object_created", "object_updated", "object_deleted"]

        },
        "creator": {
            "type": "string",
            "description": "Name of the party, which emmited this event."
        },
        "source": {
            "type": "string",
            "description": "Name of the source, algorithm or procedure, which created this event."
        },
        "payload": {
            "type": "array",
            "description": "Payload information specific to the event_type. An array, containing one or more payloads of the structure matching with the event_type.",
            "items": {
                "oneOf": [
                    {
                        "$ref": "scholix_v3_software.json"
                    },
                    {
                        "$ref": "object.json"
                    }
                ]
            }
        },
        "id": {
            "type": "string",
            "description": "Globally unique identifier of the event (UUID version 4 as specified in RFC 4122)."
        },
        "time": {
            "type": "string",
            "description": "Time when the payload information was created."
        },
        "description": {
            "type": "string",
            "description": "Free-text description of the event."
        }
    },
    "required": [
      "event_type",
      "creator",
      "source",
      "payload",
      "id",
      "time"
    ]
}

=== asclepias/asclepias-broker/examples/events.json
[
  {
    "id": "41bcdb2c-9fb4-4948-a2ca-434493dc83b3",
    "event_type": "relation_created",
    "time": "1516728860",
    "creator": "ACME Inc.",
    "source": "Test",
    "payload": [
      {
        "Source": {
          "Identifier": {
            "ID": "A",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "IsIdenticalTo",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Aid",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "B",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "Cites",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "C",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "References",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "D",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "References",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Aid",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "D",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "References",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "Ap",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "HasVersion",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "Ap",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "HasVersion",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A2",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "E",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "Cites",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Ap",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "F",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "Cites",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A2",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "Aidp",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "HasVersion",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Aid",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "Aidp",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "HasVersion",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A3",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "G",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "Cites",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Aidp",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "H",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "Cites",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "A3",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "Apid",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
          "SubType": "IsIdenticalTo",
          "SubTypeSchema": "DataCite"
        },
        "Target": {
          "Identifier": {
            "ID": "Ap",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "LinkPublicationDate": "2018-01-01",
        "LinkProvider": [
          {
            "Name": "Link Provider Ltd."
          }
        ]
      },
      {
        "Source": {
          "Identifier": {
            "ID": "A2",
            "IDScheme": "DOI"
          },
          "Type": {
            "Name": "unknown"
          }
        },
        "RelationshipType": {
          "Name": "IsRelatedTo",
